parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    dockerapi.authentication_registry:
        class: 'Jane\OpenApiRuntime\Client\Plugin\AuthenticationRegistry'
        arguments:
            $authenticationPlugins:
                - '@ConnectHolland\DockerApiBundle\Authentication\HubAuthAuthentication'
                - '@ConnectHolland\DockerApiBundle\Authentication\RegistryAuthAuthentication'

    ConnectHolland\DockerApiBundle\Authentication\HubAuthAuthentication:
        arguments:
            $username: '%env(default:dockerapi.username:DOCKER_API_USERNAME)%'
            $token: '%env(default:dockerapi.token:DOCKER_API_TOKEN)%'

    ConnectHolland\DockerApiBundle\Plugins\FixManifestResponseContentTypePlugin: ~

    ConnectHolland\DockerApiBundle\Authentication\RegistryAuthAuthentication:
        arguments:
            $username: '%env(default:dockerapi.username:DOCKER_API_USERNAME)%'
            $token: '%env(default:dockerapi.token:DOCKER_API_TOKEN)%'

    ConnectHolland\DockerApiBundle\Api\Client:
        public: true
        lazy: true
        factory: [ConnectHolland\DockerApiBundle\Api\Client, create]
        arguments:
            $httpClient: ~
            $additionalPlugins: ['@dockerapi.authentication_registry', '@ConnectHolland\DockerApiBundle\Plugins\FixManifestResponseContentTypePlugin']
