parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    dockerhubapi.authentication_registry:
        class: 'Jane\OpenApiRuntime\Client\Plugin\AuthenticationRegistry'
        arguments:
            $authenticationPlugins:
                - '@ConnectHolland\DockerHubApiBundle\Authentication\HubAuthAuthentication'
                - '@ConnectHolland\DockerHubApiBundle\Authentication\RegistryAuthAuthentication'

    ConnectHolland\DockerHubApiBundle\Authentication\HubAuthAuthentication:
        arguments:
            $username: '%env(default:dockerhubapi.username:DOCKER_HUB_API_USERNAME)%'
            $token: '%env(default:dockerhubapi.token:DOCKER_HUB_API_TOKEN)%'

    ConnectHolland\DockerHubApiBundle\Plugins\FixManifestResponseContentTypePlugin: ~

    ConnectHolland\DockerHubApiBundle\Authentication\RegistryAuthAuthentication:
        arguments:
            $username: '%env(default:dockerhubapi.username:DOCKER_HUB_API_USERNAME)%'
            $token: '%env(default:dockerhubapi.token:DOCKER_HUB_API_TOKEN)%'

    ConnectHolland\DockerHubApiBundle\Api\Client:
        public: true
        lazy: true
        factory: [ConnectHolland\DockerHubApiBundle\Api\Client, create]
        arguments:
            $httpClient: ~
            $additionalPlugins: ['@dockerhubapi.authentication_registry', '@ConnectHolland\DockerHubApiBundle\Plugins\FixManifestResponseContentTypePlugin']
